apiVersion: apps/v1
kind: Deployment
metadata:
  name: factaboutcats-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factaboutcats
  template:
    metadata:
      labels:
        app: factaboutcats
    spec:
      containers:
      - name: factaboutcats
        image: bennytrsl1/factaboutcats:2.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: factaboutcats-service
spec:
  type: LoadBalancer
  selector:
    app: factaboutcats
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000