name: Build and Test Dockerized Node.js App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: docker build -t my-node-app .

    - name: Run Docker Container
      run: docker run -d -p 3000:3000 --name test-node-app my-node-app

    - name: Wait for Node.js App to Start
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:3000 > /dev/null; then
            echo "App is reachable!"
            exit 0
          fi
          echo "Waiting for app to be reachable..."
          sleep 3
        done
        echo "App failed to start"
        docker logs test-node-app
        exit 1

    - name: Stop Container
      if: always()
      run: docker stop test-node-app && docker rm test-node-app
      
    - name: Remove Docker Image
      if: always()
      run: docker rmi my-node-app || true
